federationOperator -> leagueRailCore "manage the federation"
clubAdministrator -> leagueRailCore "manage the club"
athlete -> leagueRailCore "manage their athletic activities"
fan -> leagueRailCore "follow their favorite teams"
sponsor -> leagueRailCore "manage their sponsorship deals"
venueOperator -> leagueRailCore "manage the venue"
provider -> leagueRailCore "provide services"
financeOperator -> leagueRailCore "manage financial operations"
auditor -> leagueRailCore "perform audits"